Add config for deletes
NYPL/sierraUpdatePollerV2 pull request #35
Opened 2022-04-26 20:27 UTC by danamansana

This PR adds capability for the Sierra Update Poller to be configured for Deletes as well as updates. Right now, the current terraform configuration (and travis) is extremely repetitive, but I haven't figured out a way to fix that. If someone knows a way, please let me know.

Added some tests and changed a couple of the existing tests

2022-04-26 21:19 UTC, mwbenowitz requested changes
Turns out I was wrong and the test suite is failing because the `with(...)` does assert correctly in the tests. See comment for the specific issue.

I'm reviewing this just for the application code and not for any of the terraform or other configuration. Let me know if you want to go over that, I just don't know it well enough to confidently give any insight into it.

2022-04-26 21:19 UTC, mwbenowitz commented on lib/sierra_manager.rb
> +    update_params = ENV['UPDATE_TYPE'] == 'delete' ? _delete_params : update_params
The last `update_params` here should be `_update_params` I think (source of at least one test error)

2022-04-26 21:19 UTC, mwbenowitz commented on lib/sierra_manager.rb
> +  end
Minor, but it might be better to generate the current date value at the same time as the `@current_time` and just set it to `@current_date`. It doesn't get invoked a ton, but seems like the best approach when we know the date will/can not change

2022-04-27 17:10 UTC, danamansana commented on lib/sierra_manager.rb
> +    update_params = ENV['UPDATE_TYPE'] == 'delete' ? _delete_params : update_params
Thanks, good catch!

2022-04-27 17:10 UTC, danamansana commented on lib/sierra_manager.rb
> +  end
My reservation about this approach is that the `@current_time` gets set in multiple places, and I would worry about the two coming out of sync.

2022-04-27 20:58 UTC, mwbenowitz commented on lib/sierra_manager.rb
> +  end
That makes sense! I don't _love_ that that's the way I set that up...but almost certainly more trouble than it's worth at the moment.

2022-05-04 18:37 UTC, danamansana commented on .travis.yml
> +    - echo "Deploying Item Update to qa"
Fixed

2022-05-04 18:37 UTC, danamansana commented on .travis.yml
> +    - terraform -chdir=provisioning/production/item_update init -input=false
Fixed

2022-05-04 18:37 UTC, danamansana commented on config/item-delete-qa.env
> +RECORD_FIELDS=default,fixedFields,varFields,normTitle,normAuthor,orders,locations
Fixed

2022-05-04 18:38 UTC, danamansana commented on config/item-delete-production.env
> +RECORD_FIELDS=default,fixedFields,varFields,normTitle,normAuthor,orders,locations
Looks like the existing configuration for item updates in qa/prod doesn't use those limited fields. Should that be updated?

2022-05-04 18:38 UTC, danamansana commented on lib/sierra_manager.rb
> +     ["deletedDate", "[#{@state.start_time},#{_current_date}]"]
Actually, as long as this is set up to use a different state file from the updater, I don't think `@state.start_time` will be a full datetime.

`@state.start_time` is fetched from the `last_execution_time` in `state_manager.rb`, which is set by `set_current_state`, and we are setting the state using `_current_date`, so it should be just a date. Right?

2022-05-04 18:38 UTC, danamansana commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
OK I looked at this again and it looks like I actually built this with the assumption of different buckets, e.g. in `item-delete-production.env` there is this:

```
BUCKET_NAME=sierra-delete-poller-state-production
```
Does that seem like it would work? Is it a bad idea?

2022-05-04 21:06 UTC, nonword commented on lib/sierra_manager.rb
> +     ["deletedDate", "[#{@state.start_time},#{_current_date}]"]
That sounds right, provided you're using different state files

2022-05-04 21:09 UTC, nonword commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
That could work, but that's a lot of buckets, which would have to be created manually with identical permissions, etc. I feel like, ideally, we keep the existing two buckets: [sierra-poller-state-production](https://s3.console.aws.amazon.com/s3/buckets/sierra-poller-state-production?region=us-east-1) and [sierra-poller-state-qa](https://s3.console.aws.amazon.com/s3/buckets/sierra-poller-state-qa?region=us-east-1)

2022-05-04 21:12 UTC, nonword commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
`SCHEMA_TYPE` always felt like a surprising S3 key to use, but, although it's also a little convoluted, I think `#{RECORD_TYPE}-#{UPDATE_TYPE}-poller-state.json` would be a nice key as it cleanly identifies the poller and would scan nicely to one just looking at the S3 files

2022-05-05 13:51 UTC, charmingduchess commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
would an alternative be to have a last_deletion_time and last_update_time instead of just last_execution_time?

2022-05-05 14:32 UTC, nonword commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
@charmingduchess Is that a means to use a single state file? I'd be nervous about two separate deployments sharing a state file because one may overwrite the other's change.

2022-05-05 18:18 UTC, danamansana commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
OK, I've changed this so that the buckets are the same across deployments, but the state files are separate for update vs delete, and can be set directly by using the `S3_KEY` env variable. I've updated the config so that the file name will not change for bib/item updates, so as to keep the changes in this PR limited to delete pollers, and I've changed the `S3_KEY` for the delete pollers to be delete-specific. Personally I prefer having `S3_KEY` directly configured rather than derived, @nonword  let me know what you think.

2022-05-05 20:29 UTC, nonword commented on lib/state_manager.rb
> +        key: "#{ENV['S3_KEY'].downcase}_poller_status.json",
With the move to explicitly configure `S3_KEY`, seems strange that we're downcasing it here. Could we drop the `.downcase` so that `S3_KEY` better matches the actual S3 key? (Entails changing the `S3_KEY` values in the config files to be pre downcased.) If we want to be fully explicit, I could see changing the entire actual S3 key be included in the `S3_KEY` (e.g. `S3_KEY=bibdelete_poller_status.json`)

2022-05-05 20:29 UTC, nonword commented on lib/sierra_manager.rb
> +      @state.set_current_state(ENV['UPDATE_TYPE'] == 'delete' ? _current_date : current_time, 0)
I'm happy with explicit over derived; Only risk is typos. But I don't think it's necessary to keep the S3 filenames the same as before for the update poller. The use of outgoing schema name always seemed an odd choice (let me know if there's a rationale for that I'm overlooking). I think ideally the filenames in S3 should make it very clear what app they refer to ("BibPostRequest" for bib-update-poller, "BibDelete" for bib-delete-poller seems an unnecessary asymmetry and subtle tech debt). The responsibilities of the app are expanding, so it's natural we'd need to refactor the state system. I'd vote for choosing the best `S3_KEY` values regardless of precedent. "bibupdate" and "bibdelete" seem fine. We'd just need to copy the existing poller keys to the new paths just before deploying to minimize redundant querying.

2022-05-26 15:18 UTC, merged